# Generated by Django 4.2.13 on 2026-06-16 08:10

from django.db import migrations, models
import django.db.models.deletion
import kavalakat.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=255, verbose_name='Event Name')),
                ('slug', models.SlugField(blank=True, max_length=280, unique=True)),
                ('short_description', models.CharField(blank=True, help_text='Brief teaser shown on event cards', max_length=500)),
                ('description', models.TextField(blank=True, help_text='Full event details shown in popup / detail page', verbose_name='Full Description')),
                ('is_featured', models.BooleanField(db_index=True, default=False, help_text='Featured events appear first')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], db_index=True, default='draft', max_length=12)),
                ('tag', models.CharField(blank=True, help_text='Pill label on card e.g. Expo, Workshop. Auto-filled from category.', max_length=80)),
                ('featured_image', models.ImageField(blank=True, help_text='Card thumbnail — JPG/JPEG/PNG/WEBP max 5 MB', null=True, upload_to='events/featured/', validators=[kavalakat.validators.validate_image_file])),
                ('organizer', models.CharField(blank=True, max_length=255)),
                ('organizer_logo', models.ImageField(blank=True, help_text='JPG/JPEG/PNG/WEBP max 5 MB', null=True, upload_to='events/organizer_logos/', validators=[kavalakat.validators.validate_image_file])),
                ('event_date', models.DateTimeField(db_index=True, verbose_name='Event Date')),
                ('event_time', models.CharField(blank=True, help_text='e.g. 10:00 AM – 6:00 PM', max_length=100)),
                ('venue', models.CharField(blank=True, help_text='Venue name', max_length=255)),
                ('location', models.CharField(blank=True, help_text='City / full address', max_length=255)),
                ('registration_url', models.CharField(blank=True, help_text='Full URL or relative path e.g. /contact', max_length=500, verbose_name='Registration Link')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
                'ordering': ['-is_featured', '-event_date'],
            },
        ),
        migrations.CreateModel(
            name='EventCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Category Name')),
                ('slug', models.SlugField(blank=True, max_length=170, unique=True)),
                ('description', models.TextField(blank=True, help_text='Shown on the category detail page')),
                ('icon', models.CharField(blank=True, help_text='Font Awesome class e.g. fa-calendar-star', max_length=80)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Event Category',
                'verbose_name_plural': 'Event Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='EventImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='JPG/JPEG/PNG/WEBP max 5 MB', upload_to='events/gallery/', validators=[kavalakat.validators.validate_image_file])),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('order', models.PositiveSmallIntegerField(default=0, help_text='Lower = first')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='events.event')),
            ],
            options={
                'verbose_name': 'Event Gallery Image',
                'verbose_name_plural': 'Event Gallery Images',
                'ordering': ['order', 'uploaded_at'],
            },
        ),
        migrations.AddField(
            model_name='event',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='events.eventcategory', verbose_name='Event Category'),
        ),
    ]
