# Generated by Django 4.2.13 on 2026-06-16 06:07

from django.db import migrations, models
import django.db.models.deletion
import kavalakat.validators


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='JPG, JPEG, PNG or WEBP — max 5 MB', upload_to='events/gallery/', validators=[kavalakat.validators.validate_image_file])),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('order', models.PositiveSmallIntegerField(default=0, help_text='Display order (lower = first)')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Event Gallery Image',
                'verbose_name_plural': 'Event Gallery Images',
                'ordering': ['order', 'uploaded_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['-is_featured', '-event_date', '-created_at'], 'verbose_name': 'Event', 'verbose_name_plural': 'Events'},
        ),
        migrations.RemoveIndex(
            model_name='event',
            name='events_even_status_5709b6_idx',
        ),
        migrations.RemoveIndex(
            model_name='event',
            name='events_even_event_d_2c2da5_idx',
        ),
        migrations.AddField(
            model_name='event',
            name='event_time',
            field=models.CharField(blank=True, help_text='Human-readable time (e.g. 10:00 AM – 6:00 PM)', max_length=100),
        ),
        migrations.AddField(
            model_name='event',
            name='is_featured',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='event',
            name='location',
            field=models.CharField(blank=True, help_text='City / address (e.g. Kochi, Kerala)', max_length=255),
        ),
        migrations.AddField(
            model_name='event',
            name='organizer',
            field=models.CharField(blank=True, help_text='Organising company / person name', max_length=255),
        ),
        migrations.AddField(
            model_name='event',
            name='organizer_logo',
            field=models.ImageField(blank=True, help_text='JPG, JPEG, PNG or WEBP — max 5 MB', null=True, upload_to='events/organizer_logos/', validators=[kavalakat.validators.validate_image_file]),
        ),
        migrations.AddField(
            model_name='event',
            name='registration_url',
            field=models.URLField(blank=True, help_text='External registration link, or /contact'),
        ),
        migrations.AddField(
            model_name='event',
            name='tag',
            field=models.CharField(blank=True, help_text='Short label shown on event card (e.g. Expo, Workshop)', max_length=80),
        ),
        migrations.AddField(
            model_name='event',
            name='venue',
            field=models.CharField(blank=True, help_text='Venue name (e.g. International Trade Fair Complex)', max_length=255),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='featured_image',
            field=models.ImageField(blank=True, help_text='JPG, JPEG, PNG or WEBP — max 5 MB. Used as card thumbnail.', null=True, upload_to='events/featured/', validators=[kavalakat.validators.validate_image_file]),
        ),
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], db_index=True, default='active', max_length=10),
        ),
        migrations.AddField(
            model_name='eventimage',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='events.event'),
        ),
    ]
