# Generated by Django 4.2.13 on 2026-06-16 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_eventimage_alter_event_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='registration_url',
            field=models.CharField(blank=True, help_text='Full URL (https://…) or relative path (/contact)', max_length=500),
        ),
    ]
