# Generated by Django 4.2.13 on 2026-06-16 09:13

from django.db import migrations, models
import kavalakat.validators


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_registration_url_charfield'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['-is_featured', '-event_date'], 'verbose_name': 'Event', 'verbose_name_plural': 'Events'},
        ),
        migrations.AlterField(
            model_name='event',
            name='event_date',
            field=models.DateTimeField(db_index=True, verbose_name='Event Date'),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_time',
            field=models.CharField(blank=True, help_text='e.g. 10:00 AM – 6:00 PM', max_length=100),
        ),
        migrations.AlterField(
            model_name='event',
            name='featured_image',
            field=models.ImageField(blank=True, help_text='Card thumbnail — JPG/JPEG/PNG/WEBP max 5 MB', null=True, upload_to='events/featured/', validators=[kavalakat.validators.validate_image_file]),
        ),
        migrations.AlterField(
            model_name='event',
            name='is_featured',
            field=models.BooleanField(db_index=True, default=False, help_text='Featured events appear first'),
        ),
        migrations.AlterField(
            model_name='event',
            name='location',
            field=models.CharField(blank=True, help_text='City / full address', max_length=255),
        ),
        migrations.AlterField(
            model_name='event',
            name='organizer',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='event',
            name='organizer_logo',
            field=models.ImageField(blank=True, help_text='JPG/JPEG/PNG/WEBP max 5 MB', null=True, upload_to='events/organizer_logos/', validators=[kavalakat.validators.validate_image_file]),
        ),
        migrations.AlterField(
            model_name='event',
            name='registration_url',
            field=models.CharField(blank=True, help_text='Full URL or relative path e.g. /contact', max_length=500, verbose_name='Registration Link'),
        ),
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], db_index=True, default='draft', max_length=12),
        ),
        migrations.AlterField(
            model_name='event',
            name='tag',
            field=models.CharField(blank=True, help_text='Pill label on card e.g. Expo, Workshop. Auto-filled from category.', max_length=80),
        ),
        migrations.AlterField(
            model_name='event',
            name='venue',
            field=models.CharField(blank=True, help_text='Venue name', max_length=255),
        ),
        migrations.AlterField(
            model_name='eventimage',
            name='image',
            field=models.ImageField(help_text='JPG/JPEG/PNG/WEBP max 5 MB', upload_to='events/gallery/', validators=[kavalakat.validators.validate_image_file]),
        ),
        migrations.AlterField(
            model_name='eventimage',
            name='order',
            field=models.PositiveSmallIntegerField(default=0, help_text='Lower = first'),
        ),
    ]
