# Generated by Django 4.2.13 on 2026-05-25 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='enquiry',
            options={'ordering': ['-created_at'], 'verbose_name': 'Enquiry'},
        ),
        migrations.RemoveField(
            model_name='enquiry',
            name='company',
        ),
        migrations.RemoveField(
            model_name='enquiry',
            name='enquiry_type',
        ),
        migrations.AddField(
            model_name='enquiry',
            name='terms_accepted',
            field=models.BooleanField(default=False, verbose_name='Terms & Conditions Accepted'),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='message',
            field=models.TextField(verbose_name='Message'),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Full Name'),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='phone',
            field=models.CharField(max_length=20, verbose_name='Phone'),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='subject',
            field=models.CharField(blank=True, max_length=255, verbose_name='Subject'),
        ),
    ]
