# Generated by Django 4.2.13 on 2026-05-25 06:20

# from django.db import migrations, models


# class Migration(migrations.Migration):

#     dependencies = [
#         ('contact', '0001_initial'),
#     ]

#     operations = [
#         migrations.AlterModelOptions(
#             name='enquiry',
#             options={'ordering': ['-created_at'], 'verbose_name': 'Enquiry'},
#         ),
#         migrations.RemoveField(
#             model_name='enquiry',
#             name='company',
#         ),
#         migrations.RemoveField(
#             model_name='enquiry',
#             name='enquiry_type',
#         ),
#         migrations.AddField(
#             model_name='enquiry',
#             name='terms_accepted',
#             field=models.BooleanField(default=False, verbose_name='Terms & Conditions Accepted'),
#         ),
#         migrations.AlterField(
#             model_name='enquiry',
#             name='email',
#             field=models.EmailField(max_length=254, verbose_name='Email'),
#         ),
#         migrations.AlterField(
#             model_name='enquiry',
#             name='message',
#             field=models.TextField(verbose_name='Message'),
#         ),
#         migrations.AlterField(
#             model_name='enquiry',
#             name='name',
#             field=models.CharField(max_length=255, verbose_name='Full Name'),
#         ),
#         migrations.AlterField(
#             model_name='enquiry',
#             name='phone',
#             field=models.CharField(max_length=20, verbose_name='Phone'),
#         ),
#         migrations.AlterField(
#             model_name='enquiry',
#             name='subject',
#             field=models.CharField(blank=True, max_length=255, verbose_name='Subject'),
#         ),
#     ]




from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    """
    Adds JobApplication model.
    Updates Enquiry: removes company+enquiry_type, adds terms_accepted, makes phone required.
    """
    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        # ── Add JobApplication model ───────────────────────────────────────
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id',           models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('career',       models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications', to='contact.career')),
                ('name',         models.CharField(max_length=255)),
                ('email',        models.EmailField()),
                ('phone',        models.CharField(max_length=20)),
                ('resume',       models.FileField(upload_to='applications/resumes/')),
                ('cover_letter', models.TextField()),
                ('status',       models.CharField(choices=[('new','New'),('reviewed','Reviewed'),('shortlisted','Shortlisted'),('rejected','Rejected'),('hired','Hired')], default='new', max_length=20)),
                ('admin_note',   models.TextField(blank=True)),
                ('ip_address',   models.GenericIPAddressField(blank=True, null=True)),
                ('created_at',   models.DateTimeField(auto_now_add=True)),
                ('updated_at',   models.DateTimeField(auto_now=True)),
            ],
            options={'ordering': ['-created_at'], 'verbose_name': 'Job Application'},
        ),

        # ── Update Enquiry model ───────────────────────────────────────────
        # Add terms_accepted
        migrations.AddField(
            model_name='enquiry',
            name='terms_accepted',
            field=models.BooleanField(default=False),
        ),
        # Make phone required
        migrations.AlterField(
            model_name='enquiry',
            name='phone',
            field=models.CharField(max_length=20),
        ),
        # Remove company (if it exists)
        migrations.RemoveField(model_name='enquiry', name='company'),
        # Remove enquiry_type (if it exists)
        migrations.RemoveField(model_name='enquiry', name='enquiry_type'),
    ]
