# Generated by Django 4.2.13 on 2026-05-25 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_alter_enquiry_options_remove_enquiry_company_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='enquiry',
            options={'ordering': ['-created_at'], 'verbose_name': 'Enquiry'},
        ),
    ]
