# Generated by Django 4.2.13 on 2026-06-16 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_alter_enquiry_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch_name', models.CharField(help_text='e.g. THRISSUR, PALAKKAD, KANNUR', max_length=150)),
                ('address', models.TextField()),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('whatsapp', models.CharField(blank=True, help_text='WhatsApp number with country code', max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('google_map_link', models.URLField(blank=True, help_text='Google Maps share link')),
                ('working_hours', models.CharField(blank=True, help_text='e.g. Mon–Sat 9 AM – 6 PM', max_length=255)),
                ('display_order', models.PositiveSmallIntegerField(default=0, help_text='Lower number shown first')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Contact Location',
                'verbose_name_plural': 'Contact Locations',
                'ordering': ['display_order', 'branch_name'],
            },
        ),
    ]
