# Generated by Django 4.2.13 on 2026-06-16 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0004_add_contactlocation'),
        ('contact', '0004_branchlocation'),
    ]

    operations = [
    ]
