# Generated by Django 4.2.13 on 2026-06-16 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0005_merge_0004_add_contactlocation_0004_branchlocation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BranchLocation',
        ),
    ]
