# Generated by Django 4.2.13 on 2026-05-25 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='icon',
            field=models.CharField(blank=True, help_text='FontAwesome class', max_length=100),
        ),
        migrations.AlterField(
            model_name='servicecategory',
            name='color',
            field=models.CharField(blank=True, default='#0284f0', help_text='Hex color e.g. #f97316', max_length=20),
        ),
        migrations.AlterField(
            model_name='servicecategory',
            name='icon',
            field=models.CharField(blank=True, help_text='FontAwesome class e.g. fa-solid fa-building', max_length=100),
        ),
        migrations.AlterField(
            model_name='servicecounter',
            name='counter_number',
            field=models.CharField(help_text='e.g. 4+, 100%, 24/7', max_length=50),
        ),
        migrations.AlterField(
            model_name='servicenearbyplace',
            name='distance',
            field=models.CharField(blank=True, help_text='e.g. 2 km, 500 m', max_length=100),
        ),
    ]
