# Generated by Django 4.2.13 on 2026-06-02 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatbotFAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(help_text='e.g. What services do you offer?', max_length=500)),
                ('answer', models.TextField(help_text='The reply the chatbot will give.')),
                ('keywords', models.CharField(blank=True, help_text='Comma-separated trigger words e.g. service,offer,provide', max_length=500)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Chatbot FAQ',
                'verbose_name_plural': 'Chatbot FAQs',
                'ordering': ['order', 'question'],
            },
        ),
        migrations.AlterField(
            model_name='chatsession',
            name='session_key',
            field=models.CharField(db_index=True, max_length=120, unique=True),
        ),
    ]
