# Generated by Django 4.2.13 on 2026-07-13 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_chatlead'),
        ('chat', '0003_lead'),
    ]

    operations = [
    ]
