# Generated by Django 4.2.13 on 2026-06-11 09:47

from django.db import migrations, models
import kavalakat.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BranchLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch_name', models.CharField(max_length=150)),
                ('address', models.TextField()),
                ('phone_number', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('google_map_link', models.URLField(blank=True, help_text='Google Maps share / embed link')),
                ('location_image', models.ImageField(blank=True, help_text='JPG, JPEG, PNG or WEBP. Max size 5 MB.', null=True, upload_to='branches/locations/', validators=[kavalakat.validators.validate_image_file])),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Branch Location',
                'verbose_name_plural': 'Branch Locations',
                'ordering': ['branch_name'],
            },
        ),
    ]
