# Generated by Django 4.2.13 on 2026-06-01 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='bottom_html',
            field=models.TextField(blank=True, help_text='Raw HTML injected at the bottom of the post (embeds, CTAs, widgets, etc.)', verbose_name='Bottom HTML Section'),
        ),
    ]
