# Generated by Django 4.2.13 on 2026-06-16 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_bottom_html'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='bottom_html',
            field=models.TextField(blank=True, help_text='Raw HTML injected below the main post content on the public page.'),
        ),
    ]
