# Generated by Django 4.2.13 on 2026-04-28 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_teammember_strength_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='milestone',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='about/milestones/'),
        ),
        migrations.AddField(
            model_name='milestone',
            name='tags',
            field=models.CharField(blank=True, help_text='Comma-separated tags e.g. Cement, Thrissur', max_length=500),
        ),
    ]
