# Generated by Django 4.2.13 on 2026-04-28 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0003_milestone_image_milestone_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='client_location',
            field=models.CharField(blank=True, help_text='e.g. Kochi, Kerala', max_length=255),
        ),
        migrations.AddField(
            model_name='project',
            name='client_logo',
            field=models.ImageField(blank=True, null=True, upload_to='about/projects/logos/'),
        ),
        migrations.AddField(
            model_name='project',
            name='contact_url',
            field=models.URLField(blank=True, help_text='GET IN TOUCH link URL'),
        ),
        migrations.AddField(
            model_name='project',
            name='tag',
            field=models.CharField(blank=True, help_text='Badge shown on image e.g. PHASE 1, THRISSUR', max_length=100),
        ),
    ]
