# Generated by Django 4.2.13 on 2026-04-28 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0004_project_client_location_project_client_logo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='client_location',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
