# Generated by Django 4.2.13 on 2026-05-07 05:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text='Short bold label shown in blue uppercase above the quote, e.g. "OUTSTANDING MATERIAL QUALITY!"', max_length=200)),
                ('body', models.TextField(help_text='The testimonial text shown in the card body')),
                ('author_name', models.CharField(max_length=150)),
                ('author_role', models.CharField(blank=True, help_text='Job title / company, e.g. "Founder, Axleo"', max_length=200)),
                ('author_image', models.ImageField(blank=True, help_text='Author avatar photo (optional — falls back to person icon)', null=True, upload_to='portfolio/testimonials/')),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Testimonial',
                'verbose_name_plural': 'Testimonials',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='TrustedBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Short display name shown in UPPERCASE, e.g. VIZAG, SAIL', max_length=100)),
                ('logo', models.ImageField(blank=True, help_text='Brand logo shown at the top of the card', null=True, upload_to='portfolio/brands/')),
                ('description', models.TextField(help_text='Paragraph shown below the brand name on the card')),
                ('website_url', models.URLField(blank=True, help_text='Optional link to the brand website')),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order — cards are shown left-to-right, top-to-bottom')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Trusted Brand',
                'verbose_name_plural': 'Trusted Brands',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ProductFAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(help_text='Accordion button label, e.g. "Trusted Steel Supplier"', max_length=255)),
                ('answer', models.TextField(help_text='Text shown when this accordion panel is expanded')),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(blank=True, help_text='Leave blank to show on all product pages', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='faqs', to='portfolio.category')),
            ],
            options={
                'verbose_name': 'Product FAQ',
                'verbose_name_plural': 'Product FAQs',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='HeroBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(default='Products Power Progress Explore Our Offer.', max_length=255)),
                ('sub_heading', models.CharField(blank=True, max_length=255)),
                ('image', models.ImageField(help_text='Large hero image shown below the heading', upload_to='portfolio/banners/')),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(blank=True, help_text='Leave blank to use as the site-wide default banner', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hero_banners', to='portfolio.category')),
            ],
            options={
                'verbose_name': 'Hero Banner',
                'verbose_name_plural': 'Hero Banners',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
