# Generated by Django 4.2.13 on 2026-05-07 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_testimonial_trustedbrand_productfaq_herobanner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='herobanner',
            name='category',
        ),
        migrations.RemoveField(
            model_name='productfaq',
            name='category',
        ),
        migrations.DeleteModel(
            name='Testimonial',
        ),
        migrations.DeleteModel(
            name='TrustedBrand',
        ),
        migrations.DeleteModel(
            name='HeroBanner',
        ),
        migrations.DeleteModel(
            name='ProductFAQ',
        ),
    ]
