# Generated by Django 4.2.13 on 2026-05-08 06:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_remove_herobanner_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.CreateModel(
            name='TrustedBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='portfolio/brands/')),
                ('description', models.TextField()),
                ('website_url', models.URLField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(blank=True, help_text='Leave blank to show on all product pages', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='brands', to='portfolio.category')),
            ],
            options={
                'verbose_name': 'Trusted Brand',
                'verbose_name_plural': 'Trusted Brands',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text='Bold blue uppercase line e.g. "EXCELLENT QUALITY PRODUCTION!"', max_length=200)),
                ('body', models.TextField()),
                ('author_name', models.CharField(max_length=150)),
                ('author_role', models.CharField(blank=True, max_length=200)),
                ('author_image', models.ImageField(blank=True, null=True, upload_to='portfolio/testimonials/')),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(blank=True, help_text='Leave blank to show on all product pages', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='testimonials', to='portfolio.category')),
            ],
            options={
                'verbose_name': 'Testimonial',
                'verbose_name_plural': 'Testimonials',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductFAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
                ('answer', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(blank=True, help_text='Leave blank to show on all product pages', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='faqs', to='portfolio.category')),
            ],
            options={
                'verbose_name': 'Product FAQ',
                'verbose_name_plural': 'Product FAQs',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductAbout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=255)),
                ('body', models.TextField(help_text='Separate paragraphs with a blank line')),
                ('image', models.ImageField(blank=True, null=True, upload_to='portfolio/about/')),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(blank=True, help_text='Leave blank for global default', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='abouts', to='portfolio.category')),
            ],
            options={
                'verbose_name': 'Product About',
                'verbose_name_plural': 'Product About Sections',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HeroBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(default='Products Power Progress Explore Our Offer.', max_length=255)),
                ('sub_heading', models.CharField(blank=True, max_length=255)),
                ('image', models.ImageField(upload_to='portfolio/banners/')),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(blank=True, help_text='Leave blank for global default', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hero_banners', to='portfolio.category')),
            ],
            options={
                'verbose_name': 'Hero Banner',
                'verbose_name_plural': 'Hero Banners',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
