# Generated by Django 4.2.13 on 2026-05-09 06:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_alter_category_name_trustedbrand_testimonial_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonial',
            name='label',
            field=models.CharField(help_text='Bold blue uppercase heading e.g. "EXCELLENT QUALITY PRODUCTION!"', max_length=200),
        ),
        migrations.CreateModel(
            name='ItemFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_image', models.ImageField(blank=True, help_text='Large left-side warehouse/product image for the features section', null=True, upload_to='portfolio/features/')),
                ('title', models.CharField(help_text='Feature title shown as accordion label e.g. "Trusted Steel Supplier"', max_length=255)),
                ('description', models.TextField(help_text='Detail text shown when accordion is expanded')),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(blank=True, help_text='Leave blank to show on all product pages', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='item_features', to='portfolio.category')),
            ],
            options={
                'verbose_name': 'Item Feature',
                'verbose_name_plural': 'Item Features',
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
