# Generated by Django 4.2.13 on 2026-05-12 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_alter_testimonial_label_itemfeature'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='color',
            field=models.CharField(blank=True, default='blue', help_text='Accent colour key: orange, blue, green, purple, red, teal, pink', max_length=20),
        ),
        migrations.AlterField(
            model_name='herobanner',
            name='heading',
            field=models.CharField(default='Products Power Progress — Explore Our Offer.', max_length=255),
        ),
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='itemfeature',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='itemfeature',
            name='main_image',
            field=models.ImageField(blank=True, help_text='Large left-side image for the features section', null=True, upload_to='portfolio/features/'),
        ),
        migrations.AlterField(
            model_name='itemfeature',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='label',
            field=models.CharField(max_length=200),
        ),
    ]
