# Generated by Django 4.2.13 on 2026-05-12 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_category_color_alter_herobanner_heading_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='color',
            field=models.CharField(choices=[('orange', 'Orange'), ('blue', 'Blue'), ('green', 'Green'), ('purple', 'Purple'), ('red', 'Red'), ('teal', 'Teal'), ('pink', 'Pink'), ('yellow', 'Yellow'), ('gray', 'Gray')], default='blue', max_length=20),
        ),
        migrations.AlterField(
            model_name='herobanner',
            name='heading',
            field=models.CharField(default='Products Power Progress.', max_length=255),
        ),
        migrations.AlterField(
            model_name='item',
            name='tags',
            field=models.CharField(blank=True, help_text='Comma-separated', max_length=255),
        ),
        migrations.AlterField(
            model_name='itemfeature',
            name='category',
            field=models.ForeignKey(blank=True, help_text='Leave blank to show on all pages', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='item_features', to='portfolio.category'),
        ),
        migrations.AlterField(
            model_name='itemfeature',
            name='main_image',
            field=models.ImageField(blank=True, null=True, upload_to='portfolio/features/'),
        ),
        migrations.AlterField(
            model_name='productfaq',
            name='category',
            field=models.ForeignKey(blank=True, help_text='Leave blank to show on all pages', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='faqs', to='portfolio.category'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='category',
            field=models.ForeignKey(blank=True, help_text='Leave blank to show on all pages', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='testimonials', to='portfolio.category'),
        ),
        migrations.AlterField(
            model_name='trustedbrand',
            name='category',
            field=models.ForeignKey(blank=True, help_text='Leave blank to show on all pages', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='brands', to='portfolio.category'),
        ),
    ]
