# Generated by Django 4.2.13 on 2026-05-12 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_alter_category_color_alter_herobanner_heading_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='color',
        ),
        migrations.AlterField(
            model_name='herobanner',
            name='heading',
            field=models.CharField(default='Products Power Progress Explore Our Offer.', max_length=255),
        ),
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(help_text='Displayed in UPPERCASE on the website', max_length=255),
        ),
        migrations.AlterField(
            model_name='item',
            name='tags',
            field=models.CharField(blank=True, help_text='Comma-separated keywords', max_length=255),
        ),
        migrations.AlterField(
            model_name='itemfeature',
            name='category',
            field=models.ForeignKey(blank=True, help_text='Leave blank to show on all product pages', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='item_features', to='portfolio.category'),
        ),
        migrations.AlterField(
            model_name='itemfeature',
            name='description',
            field=models.TextField(help_text='Detail text shown when accordion is expanded'),
        ),
        migrations.AlterField(
            model_name='itemfeature',
            name='main_image',
            field=models.ImageField(blank=True, help_text='Large left-side warehouse/product image for the features section', null=True, upload_to='portfolio/features/'),
        ),
        migrations.AlterField(
            model_name='itemfeature',
            name='title',
            field=models.CharField(help_text='Feature title shown as accordion label e.g. "Trusted Steel Supplier"', max_length=255),
        ),
        migrations.AlterField(
            model_name='productfaq',
            name='category',
            field=models.ForeignKey(blank=True, help_text='Leave blank to show on all product pages', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='faqs', to='portfolio.category'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='category',
            field=models.ForeignKey(blank=True, help_text='Leave blank to show on all product pages', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='testimonials', to='portfolio.category'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='label',
            field=models.CharField(help_text='Bold blue uppercase heading e.g. "EXCELLENT QUALITY PRODUCTION!"', max_length=200),
        ),
        migrations.AlterField(
            model_name='trustedbrand',
            name='category',
            field=models.ForeignKey(blank=True, help_text='Leave blank to show on all product pages', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='brands', to='portfolio.category'),
        ),
    ]
