# Generated by Django 4.2.13 on 2026-05-13 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0008_remove_category_color_alter_herobanner_heading_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemfeature',
            name='category',
        ),
        migrations.RemoveField(
            model_name='productabout',
            name='category',
        ),
        migrations.RemoveField(
            model_name='productfaq',
            name='category',
        ),
        migrations.RemoveField(
            model_name='testimonial',
            name='category',
        ),
        migrations.RemoveField(
            model_name='trustedbrand',
            name='category',
        ),
        migrations.AddField(
            model_name='item',
            name='about_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='item',
            name='about_image',
            field=models.ImageField(blank=True, null=True, upload_to='portfolio/about/'),
        ),
        migrations.AddField(
            model_name='item',
            name='about_title',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='item',
            name='banner_image',
            field=models.ImageField(blank=True, help_text='Full-width banner image — 1920x600px recommended', null=True, upload_to='portfolio/banners/'),
        ),
        migrations.AddField(
            model_name='item',
            name='brands_heading',
            field=models.CharField(blank=True, help_text='e.g. Trusted Steel Brands We Supply', max_length=255),
        ),
        migrations.AddField(
            model_name='item',
            name='brands_json',
            field=models.TextField(blank=True, default='[]', help_text='JSON array: [{"title": "VIZAG", "description": "...", "logo_url": "..."}, ...]'),
        ),
        migrations.AddField(
            model_name='item',
            name='features_image',
            field=models.ImageField(blank=True, help_text='Large image shown beside feature accordion', null=True, upload_to='portfolio/features/'),
        ),
        migrations.AddField(
            model_name='item',
            name='features_json',
            field=models.TextField(blank=True, default='[]', help_text='JSON array: [{"title": "...", "description": "..."}, ...]'),
        ),
        migrations.AddField(
            model_name='item',
            name='features_title',
            field=models.CharField(blank=True, help_text='e.g. Steel Products, Cement Products', max_length=255),
        ),
        migrations.AddField(
            model_name='item',
            name='hero_title',
            field=models.CharField(blank=True, help_text='Headline shown at top of product page banner', max_length=500),
        ),
        migrations.AddField(
            model_name='item',
            name='testimonials_json',
            field=models.TextField(blank=True, default='[]', help_text='JSON array: [{"title": "...", "description": "...", "client_name": "..."}, ...]'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('Trading', 'Trading'), ('Distribution', 'Distribution'), ('Services', 'Services')], max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(help_text='Displayed UPPERCASE on website', max_length=255),
        ),
        migrations.AlterField(
            model_name='item',
            name='tags',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.DeleteModel(
            name='HeroBanner',
        ),
        migrations.DeleteModel(
            name='ItemFeature',
        ),
        migrations.DeleteModel(
            name='ProductAbout',
        ),
        migrations.DeleteModel(
            name='ProductFAQ',
        ),
        migrations.DeleteModel(
            name='Testimonial',
        ),
        migrations.DeleteModel(
            name='TrustedBrand',
        ),
    ]
