# Generated by Django 4.2.13 on 2026-06-01 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0009_remove_itemfeature_category_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['order', 'name']},
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='about_title',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='item',
            name='banner_image',
            field=models.ImageField(blank=True, null=True, upload_to='portfolio/banners/'),
        ),
        migrations.AlterField(
            model_name='item',
            name='brands_heading',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='item',
            name='brands_json',
            field=models.TextField(blank=True, default='[]'),
        ),
        migrations.AlterField(
            model_name='item',
            name='features_image',
            field=models.ImageField(blank=True, null=True, upload_to='portfolio/features/'),
        ),
        migrations.AlterField(
            model_name='item',
            name='features_json',
            field=models.TextField(blank=True, default='[]'),
        ),
        migrations.AlterField(
            model_name='item',
            name='features_title',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='item',
            name='hero_title',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='item',
            name='testimonials_json',
            field=models.TextField(blank=True, default='[]'),
        ),
    ]
