# Generated by Django 4.2.13 on 2026-06-16 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0010_alter_item_options_alter_category_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['order', 'name'], 'verbose_name': 'Portfolio Item', 'verbose_name_plural': 'Portfolio Items'},
        ),
        migrations.AlterField(
            model_name='item',
            name='about_title',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='item',
            name='banner_image',
            field=models.ImageField(blank=True, help_text='Full-width banner image — 1920x600px recommended', null=True, upload_to='portfolio/banners/'),
        ),
        migrations.AlterField(
            model_name='item',
            name='brands_heading',
            field=models.CharField(blank=True, help_text='e.g. Trusted Steel Brands We Supply', max_length=255),
        ),
        migrations.AlterField(
            model_name='item',
            name='brands_json',
            field=models.TextField(blank=True, default='[]', help_text='JSON array: [{"title": "VIZAG", "description": "...", "logo_url": "..."}, ...]'),
        ),
        migrations.AlterField(
            model_name='item',
            name='features_image',
            field=models.ImageField(blank=True, help_text='Large image shown beside feature accordion', null=True, upload_to='portfolio/features/'),
        ),
        migrations.AlterField(
            model_name='item',
            name='features_json',
            field=models.TextField(blank=True, default='[]', help_text='JSON array: [{"title": "...", "description": "..."}, ...]'),
        ),
        migrations.AlterField(
            model_name='item',
            name='features_title',
            field=models.CharField(blank=True, help_text='e.g. Steel Products, Cement Products', max_length=255),
        ),
        migrations.AlterField(
            model_name='item',
            name='hero_title',
            field=models.CharField(blank=True, help_text='Headline shown at top of product page banner', max_length=500),
        ),
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(help_text='Displayed UPPERCASE on website', max_length=255),
        ),
        migrations.AlterField(
            model_name='item',
            name='testimonials_json',
            field=models.TextField(blank=True, default='[]', help_text='JSON array: [{"title": "...", "description": "...", "client_name": "..."}, ...]'),
        ),
    ]
